# Generated by Django 4.1 on 2023-07-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the product', max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Enter a description for the product', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the product', max_digits=10, verbose_name='price')),
                ('stock', models.IntegerField(help_text='Enter the amount in stock for the product', verbose_name='stock')),
                ('image', models.ImageField(help_text='Upload an image for the product', upload_to='products/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
